version: "3"
services:
  redis:
    # replace username/repo:tag with your name and image details
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"

  history:
    # replace username/repo:tag with your name and image details
    image: history
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
    depends_on:
      - redis

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
        